version: "3"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pmg-node
    volumes:
      - ".:/var/www"
      - "/var/www/node_modules"
    ports:
      - "4200:4200"
